### ISSUE TITLE
关于ActivityNet特征

### ISSUE THREAD

**Issue by lijiannuist** [Finspire13/CMCS-Temporal-Action-Localization#1]
ActivityNet特征竟然有4,500G？百度云盘里是什么格式存放的？（想预览一下）
ActivityNet抽特征的两个模型，有没有在ActivityNet上面finetune？
UntrimmedNet 是15FPS，I3D 是16FPS, 是不是没有对齐？

**Comment by Finspire13** [comment]
@lijiannuist 
1. ActivityNet特征大约500G
2. I3D特征没有finetune，UntrimmedNet在ActivityNet v1.2 train set上训练过，[详见](https://github.com/wanglimin/UntrimmedNet/blob/master/scripts/get_reference_model_anet_train_only.sh)
3. 原始的两个特征模型是每隔15或16帧（不是15/16 FPS），实际使用间隔可能更小，详见config文件中的base_sample_rate 和sample_rate。所说的’对齐‘是指什么？

**Comment by bityangke** [comment]
Amazing work! And thanks very much for sharing! I have a question about the data file.
Why the feature file of Anet is so huge? It is nearly impossible for one to download this large file from Baidupan. The Anet I3D feature shared by https://github.com/sujoyp/wtalc-pytorch is only ~8GB. 
Thanks again.

**Comment by Finspire13** [comment]
@bityangke 
It is because ten-crop data augmentation is used (10x file size). 
And there are two type of features, i.e., I3D and UntrimmedNet. 

To download, probably you need a Baidu VIP, lol.

**Comment by Finspire13** [comment]
@bityangke 
Besides, our features are extracted for ActivityNet 1.3

**Comment by mitming** [comment]
> @bityangke
> It is because ten-crop data augmentation is used (10x file size).
> And there are two type of features, i.e., I3D and UntrimmedNet.
> 
> To download, probably you need a Baidu VIP, lol.

Hi, thanks for your contribution!

Could you please tell me why you need ten-crop data augmentation? I did not find it in your paper of supplementary material.
