### ISSUE TITLE
Number of videos in ActivityNet1.3

### ISSUE THREAD

**Issue by PeisenZhao** [Finspire13/CMCS-Temporal-Action-Localization#11]
Thanks for your great work!

I find there is 18493 video features of 'ANET_FEATURES' provided by you. 
But ActivityNet1.3 dataset has 19994 videos.
Is there something wrong?

**Comment by Finspire13** [comment]
ActivityNet only provides Youtube URLs for videos. Some URLs are dead now.

**Comment by PeisenZhao** [comment]
FYI：

**Comment by PeisenZhao** [comment]
FYI：the length of I3D features in “MvZFYjs80Y4” and "0dkIbKXXFzI" are less than the video length

**Comment by ciwei123** [comment]
@Finspire13 @PeisenZhao Could you share with me the features of anet1.3？Thank you very much!!

**Comment by PeisenZhao** [comment]
Hi! You can download the features of ant1.3 by link (https://pan.baidu.com/s/1KJxNE-_We-9AcBs0N6xTXA) which are provided by the authors.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ciwei123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 上午10:03
收件人:&nbsp;"Finspire13/CMCS-Temporal-Action-Localization"<CMCS-Temporal-Action-Localization@noreply.github.com&gt;;
抄送:&nbsp;"赵培森"<503593362@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Finspire13/CMCS-Temporal-Action-Localization] Number of videos in ActivityNet1.3 (#11)





 
@Finspire13 @PeisenZhao Could you share with me the features of anet1.3？Thank you very much!!

**Comment by ciwei123** [comment]
> Hi! You can download the features of ant1.3 by link (https://pan.baidu.com/s/1KJxNE-_We-9AcBs0N6xTXA) which are provided by the authors.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ciwei123"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月21日(星期四) 上午10:03 收件人:&nbsp;"Finspire13/CMCS-Temporal-Action-Localization"<CMCS-Temporal-Action-Localization@noreply.github.com&gt;; 抄送:&nbsp;"赵培森"<503593362@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Finspire13/CMCS-Temporal-Action-Localization] Number of videos in ActivityNet1.3 (#11) @Finspire13 @PeisenZhao Could you share with me the features of anet1.3？Thank you very much!! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much!!

**Comment by ciwei123** [comment]
@PeisenZhao @Finspire13Thanks for your sharing.I have downloaded the feature,which is 468G，30 files.And I tried the following command to unzip：
zip -F s_ANET_FEATURES.zip --out file-large.zip
unzip file-large.zip
but I get the error:
extracting: ANET_FEATURES.zip        bad CRC 180dd079  (should be c2d85689)
The files:
s_ANET_FEATURES.z01  s_ANET_FEATURES.z06  s_ANET_FEATURES.z11  s_ANET_FEATURES.z16  s_ANET_FEATURES.z21  s_ANET_FEATURES.z26 s_ANET_FEATURES.z02  s_ANET_FEATURES.z07  s_ANET_FEATURES.z12  s_ANET_FEATURES.z17  s_ANET_FEATURES.z22  s_ANET_FEATURES.z27
s_ANET_FEATURES.z03  s_ANET_FEATURES.z08  s_ANET_FEATURES.z13  s_ANET_FEATURES.z18  s_ANET_FEATURES.z23  s_ANET_FEATURES.z28 s_ANET_FEATURES.z04  s_ANET_FEATURES.z09  s_ANET_FEATURES.z14  s_ANET_FEATURES.z19  s_ANET_FEATURES.z24  s_ANET_FEATURES.z29
s_ANET_FEATURES.z05  s_ANET_FEATURES.z10  s_ANET_FEATURES.z15  s_ANET_FEATURES.z20  s_ANET_FEATURES.z25  s_ANET_FEATURES.zip
Could you tell me the reason?And whether I download the complete.

**Comment by PeisenZhao** [comment]
Try these?


Try this?






cat * &gt; single.zip


unzip single.zip







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ciwei123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上7:22
收件人:&nbsp;"Finspire13/CMCS-Temporal-Action-Localization"<CMCS-Temporal-Action-Localization@noreply.github.com&gt;;
抄送:&nbsp;"赵培森"<503593362@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Finspire13/CMCS-Temporal-Action-Localization] Number of videos in ActivityNet1.3 (#11)





 
@PeisenZhao @Finspire13Thanks for your sharing.I have downloaded the feature,which is 468G，30 files.And I tried the following command to unzip：
 zip -F s_ANET_FEATURES.zip --out file-large.zip
 unzip file-large.zip
 but I get the error:
 extracting: ANET_FEATURES.zip        bad CRC 180dd079  (should be c2d85689)
 The files:
 s_ANET_FEATURES.z01  s_ANET_FEATURES.z06  s_ANET_FEATURES.z11  s_ANET_FEATURES.z16  s_ANET_FEATURES.z21  s_ANET_FEATURES.z26 s_ANET_FEATURES.z02  s_ANET_FEATURES.z07  s_ANET_FEATURES.z12  s_ANET_FEATURES.z17  s_ANET_FEATURES.z22  s_ANET_FEATURES.z27
 s_ANET_FEATURES.z03  s_ANET_FEATURES.z08  s_ANET_FEATURES.z13  s_ANET_FEATURES.z18  s_ANET_FEATURES.z23  s_ANET_FEATURES.z28 s_ANET_FEATURES.z04  s_ANET_FEATURES.z09  s_ANET_FEATURES.z14  s_ANET_FEATURES.z19  s_ANET_FEATURES.z24  s_ANET_FEATURES.z29
 s_ANET_FEATURES.z05  s_ANET_FEATURES.z10  s_ANET_FEATURES.z15  s_ANET_FEATURES.z20  s_ANET_FEATURES.z25  s_ANET_FEATURES.zip
 Could you tell me the reason?And whether I download the complete.

**Comment by ciwei123** [comment]
@Finspire13 @PeisenZhao Thanks for your reply. I tried the following command ,and it worked.
cat input.z* > output.zip
unzip output.zip
Another question ，I get four folders:
anet_flow_intensity  
anet_i3d_feature_25fps  
anet_untri_feature_25fps  
anet_untri_feature_25fps_train_only
but I don't know the meaning of each folder and the folders，Could you tell me？Thank you very much!
