### ISSUE TITLE
No flow-resized-step16 folder in zip files

### ISSUE THREAD

**Issue by jd730** [Finspire13/CMCS-Temporal-Action-Localization#14]
HI, I successfully unzipped ANET_FEATURES files.
However, I cannot find flow-resizd-step16 in `ANET_FEATURES/anet_i3d_feature_25fps` folder.

Doesn't it originally exist on zip files? Or, should I re-download around 500GB zip files.....?

Thank you.

**Comment by Finspire13** [comment]
On my side, flow-resized-step16 is included.

**Comment by Finspire13** [comment]
The data may have corrupted. I will strikeout the link for AcitivityNet features.
