### ISSUE TITLE
Trained Model 'Page not found'

### ISSUE THREAD

**Issue by Scipio1996** [Finspire13/CMCS-Temporal-Action-Localization#2]

**Comment by Finspire13** [comment]
They are [here](https://github.com/Finspire13/Weakly-Action-Detection/tree/Release-CVPR19/models). I don't see problems. Please provide more description.

**Comment by JudeLiu** [comment]
I as well got 404 browsing https://github.com/Finspire13/Weakly-Action-Detection/tree/Release-CVPR19/models

**Comment by Finspire13** [comment]
> I as well got 404 browsing https://github.com/Finspire13/Weakly-Action-Detection/tree/Release-CVPR19/models

@ Sorry, the models are there but the link is wrongly pointed to another private repo of mine. I have fixed it.
