### ISSUE TITLE
The tool to extract optical flow and RGB frames

### ISSUE THREAD

**Issue by xzxedu** [Finspire13/CMCS-Temporal-Action-Localization#23]
Hi,

May I ask how do you format the original raw videos into 25 fps and convert them into the optical flow and RGB frames? Did you use OpenCV to do this? 

Besides, what is the _flow_x_ and _flow_y_ in your tools/get_flow_intensity.py?  Did all videos format to 25 fps and 340x256 resolution before generate the static video clips?

Cheers

**Comment by Finspire13** [comment]
Convert to 25 FPS: **ffmpeg**

Convert into the optical flow and RGB frames: **https://github.com/yjxiong/temporal-segment-networks**
