### ISSUE TITLE
ANET features

### ISSUE THREAD

**Issue by coolbay** [Finspire13/CMCS-Temporal-Action-Localization#25]
I notice that 'ActivityNet Features (Input videos are 25fps)' is crossed out. Are the features still valid to download?  Thanks very much!

**Comment by Finspire13** [comment]
Some users reported the file has corrupted. But I didn't check it.

I think the features are still valid to download, at the risk of data corruption.
So I recommend re-extracting the features.

**Comment by coolbay** [comment]
One more question. Are the Anet features you provided I3D features or UNT features? Thanks!
