### ISSUE TITLE
Regarding your paper

### ISSUE THREAD

**Issue by lianxxx** [Finspire13/CMCS-Temporal-Action-Localization#5]
Thank you first for your code.

In your ablation studies, there is a result for "No TA". During training, how was the "MIL loss" calculated in this case? (Is there an MIL loss for each branch or only one in total for the averaged of all branches or else?)

**Comment by Finspire13** [comment]
"No TA" means the temporal attention is replaced with global average/max pooling [(See here)](https://github.com/Finspire13/CMCS-Temporal-Action-Localization/blob/master/model.py#L58). 

Other configurations are the same.
