### ISSUE TITLE
thumos14, extract i3d features 

### ISSUE THREAD

**Issue by Zhuysheng** [Finspire13/CMCS-Temporal-Action-Localization#6]
When I try to extract features on thumos14 dataset by the default setting, the  length of feature  is less than yours, how do you set the chunk size and frequency

**Comment by Finspire13** [comment]
The frequency is every 5 frames (so the snippets are overlapping).
Please refer to the [config](https://github.com/Finspire13/CMCS-Temporal-Action-Localization/blob/master/configs/thumos-UNT.json#L80)

**Comment by huge123** [comment]
@Finspire13 In this case that the snippets are overlapping, why the paper says " I3D is pre-trained on Kinetics [7] and takes non-overlapping 16-frame chunks as input for both two streams" in section 4.2?

**Comment by Finspire13** [comment]
> @Finspire13 In this case that the snippets are overlapping, why the paper says " I3D is pre-trained on Kinetics [7] and takes non-overlapping 16-frame chunks as input for both two streams" in section 4.2?

@huge123 Hi, if I remember correctly, the feature snippets are overlapping at their extraction (please refer to 'base_sample_rate' in the configs), and the feature sent into the model is non-overlapping (please refer to 'sample_rate' in the configs). Such difference make it possible to augment the data temporally when training (please refer this [code](https://github.com/Finspire13/CMCS-Temporal-Action-Localization/blob/master/utils.py#L330).
