### ISSUE TITLE
problem about unzip AN features

### ISSUE THREAD

**Issue by Valarrrrr** [Finspire13/CMCS-Temporal-Action-Localization#7]
Hi, thanks for your work. I'm trying to unzip AN features but it's not working, I've been trying many days and I'm always getting an error. Could you please send me another link or provide me with the features somehow? I would really appreciate it.

**Comment by Finspire13** [comment]
The files are too large and difficult to share. I recommend you extract the features using [the code provided in the readme. Thank you.
